### ISSUE TITLE
Explicitly define the minimum Rust version expected.

### ISSUE THREAD

**Issue by larrydewey** [virtee/sev#84]
Currently we are not defining the minimum Rust version, which can cause problems when attempting to build with older versions of Rust/Cargo:

https://github.com/virtee/sev/blob/a5c9eb231cea1a1233e57b6e34a1bdd05809e364/Cargo.toml#L1-L14

It would be good to set the minimum expected version

```toml
[package]
# ...
rust-version = "1.65"
```
